# @generated by `cargo buckal`

import argparse
import os
import re
import json
from pathlib import Path
from tomllib import load
from typing import IO, NamedTuple

# This is the current buck2 project root
TOOL_CWD: str = os.path.join(os.getcwd(), "")


class Args(NamedTuple):
    vendor: Path
    workspace: Path
    out_dict: IO[str]
    out_flags: IO[str]

def arg_parse() -> Args:
    parser = argparse.ArgumentParser(description="Parse Cargo manifest")
    parser.add_argument("--vendor", type=Path, required=True)
    parser.add_argument("--workspace", type=Path)
    # Always write UTF-8 so rustc_action (the Buck2 Rust toolchain action,
    # which assumes UTF-8 response files) can parse the generated files on
    # Windows, where the locale default is typically cp1252.
    parser.add_argument("--out-dict", type=argparse.FileType("w", encoding="utf-8"), required=True)
    parser.add_argument("--out-flags", type=argparse.FileType("w", encoding="utf-8"), required=True)

    return Args(**vars(parser.parse_args()))

def main() -> None:
    args = arg_parse()

    cargo_env = {}
    with (args.vendor / "Cargo.toml").open("rb") as f:
        cargo_toml = load(f)

    cargo_env["CARGO_MANIFEST_DIR"] = str(TOOL_CWD / args.vendor)
    cargo_env["CARGO_MANIFEST_PATH"] = str(TOOL_CWD / args.vendor / "Cargo.toml")

    cargo_package = cargo_toml.get("package")
    if not cargo_package:
        raise ValueError("Cargo.toml missing [package] section")
    
    workspace_package = {}

    def load_workspace_package() -> dict:
        nonlocal workspace_package
        if workspace_package:
            return workspace_package
        if not args.workspace:
            raise ValueError("Workspace reference specified but no workspace manifest path provided")
        with args.workspace.open("rb") as f:
            workspace_cargo_toml = load(f)
        workspace_package = workspace_cargo_toml.get("workspace", {}).get("package")
        if not workspace_package:
            raise ValueError("Workspace Cargo.toml missing [workspace.package] section")
        return workspace_package

    # Handle keys that may inherit from the workspace
    # See https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
    workspace_package_key = {
        "version",
        "authors",
        "description",
        "homepage",
        "repository",
        "rust-version",
        "license",
        "license-file",
        "readme",
    }
    inherited_from_workspace = set()
    for key in workspace_package_key:
        value = cargo_package.get(key)
        if isinstance(value, dict) and value.get("workspace") is True:
            workspace_values = load_workspace_package()
            workspace_value = workspace_values.get(key)
            if workspace_value is None:
                raise ValueError(
                    f"Workspace inheritance requested for key '{key}' but "
                    f"'[workspace.package]' does not define it"
                )
            cargo_package[key] = workspace_value
            inherited_from_workspace.add(key)

    # Parse semantic versioning
    semver_pattern = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$")

    cargo_env["CARGO_PKG_VERSION"] = cargo_package["version"]

    semver_match = semver_pattern.match(cargo_package["version"])
    if semver_match:
        major, minor, patch, pre, build = semver_match.groups()
        cargo_env["CARGO_PKG_VERSION_MAJOR"] = major
        cargo_env["CARGO_PKG_VERSION_MINOR"] = minor
        cargo_env["CARGO_PKG_VERSION_PATCH"] = patch
        cargo_env["CARGO_PKG_VERSION_PRE"] = pre if pre else ""

    cargo_env["CARGO_PKG_AUTHORS"] = ":".join(cargo_package.get("authors", []))
    cargo_env["CARGO_PKG_NAME"] = cargo_package["name"]
    cargo_env["CARGO_PKG_DESCRIPTION"] = cargo_package.get("description", "")
    cargo_env["CARGO_PKG_HOMEPAGE"] = cargo_package.get("homepage", "")
    cargo_env["CARGO_PKG_REPOSITORY"] = cargo_package.get("repository", "")
    cargo_env["CARGO_PKG_RUST_VERSION"] = cargo_package.get("rust-version", "")
    cargo_env["CARGO_PKG_LICENSE"] = cargo_package.get("license", "")
    # Cargo interprets `readme = true` as "README.md" and `readme = false` as ""
    # (see https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field).
    # A plain string is used as-is.
    readme = cargo_package.get("readme", "")
    if readme is True:
        readme = "README.md"
    elif readme is False:
        readme = ""

    license_file = cargo_package.get("license-file", "")

    # Emit absolute paths for readme and license-file so build scripts can
    # locate the files regardless of their (synthetic) working directory.
    # For workspace-inherited values the path is relative to the workspace root;
    # for member-local values it is relative to the vendor directory.
    # NOTE: args.workspace must point to the real workspace Cargo.toml (not a
    # buck-out copy) for inherited paths to resolve correctly — ensure the
    # cargo-buckal export_file rule uses mode = "reference".
    if readme:
        if "readme" in inherited_from_workspace and args.workspace:
            readme = str((args.workspace.parent / readme).resolve())
        else:
            readme = str((TOOL_CWD / args.vendor / readme).resolve())
    if license_file:
        if "license-file" in inherited_from_workspace and args.workspace:
            license_file = str((args.workspace.parent / license_file).resolve())
        else:
            license_file = str((TOOL_CWD / args.vendor / license_file).resolve())

    cargo_env["CARGO_PKG_README"] = str(readme)
    cargo_env["CARGO_PKG_LICENSE_FILE"] = str(license_file)

    def to_ascii_escaped(value: str) -> str:
        return value.encode("ascii", "backslashreplace").decode("ascii")

    env_flags = ""
    for key, value in cargo_env.items():
        if key == "CARGO_PKG_DESCRIPTION":
            # Escape newlines and quotes in description
            value = value.replace("\n", "\\n").replace('"', '\\"')
            env_flags += f"--env-set={key}=\"{to_ascii_escaped(value)}\"\n"
        else:
            env_flags += f"--env-set={key}={to_ascii_escaped(value)}\n"
    args.out_flags.write(env_flags)

    if cargo_package.get("links"):
        cargo_env["CARGO_MANIFEST_LINKS"] = cargo_package.get("links")

    json.dump(cargo_env, args.out_dict, indent=2)


if __name__ == "__main__":
    main()
